create table if not exists scans (
  id bigint generated by default as identity primary key,
  user_id uuid,
  user_email text not null,
  product_name text not null,
  mode text not null,
  ingredients text not null,
  risk_score integer not null,
  confidence integer not null,
  judgment text not null,
  macros jsonb default '{}'::jsonb,
  matches jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create index if not exists scans_user_email_created_at_idx
on scans (user_email, created_at desc);

alter table scans enable row level security;

drop policy if exists "Users can read own scans" on scans;
create policy "Users can read own scans"
on scans
for select
using (
  auth.jwt() ->> 'email' = user_email
);

drop policy if exists "Users can insert own scans" on scans;
create policy "Users can insert own scans"
on scans
for insert
with check (
  auth.jwt() ->> 'email' = user_email
);
