import '../../shared/models/trigger_model.dart';

const List<TriggerModel> kTriggerDatabase = [
  TriggerModel(ingredient: 'sugar', severity: TriggerSeverity.high, category: TriggerCategory.gut, reason: 'Directly feeds Malassezia yeast overgrowth', affects: [TriggerAffect.skin, TriggerAffect.hair]),
  TriggerModel(ingredient: 'high fructose corn syrup', severity: TriggerSeverity.high, category: TriggerCategory.gut, reason: 'Rapid glucose spike fuels yeast growth', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'maltodextrin', severity: TriggerSeverity.high, category: TriggerCategory.gut, reason: 'Higher GI than sugar, disrupts gut microbiome', affects: [TriggerAffect.skin, TriggerAffect.hair]),
  TriggerModel(ingredient: 'dextrose', severity: TriggerSeverity.high, category: TriggerCategory.gut, reason: 'Pure glucose, immediate yeast fuel', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'corn syrup', severity: TriggerSeverity.high, category: TriggerCategory.gut, reason: 'High glycemic index, promotes yeast feeding', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'polysorbate 80', severity: TriggerSeverity.high, category: TriggerCategory.gut, reason: 'Emulsifier that degrades the gut mucus layer', affects: [TriggerAffect.skin, TriggerAffect.hair]),
  TriggerModel(ingredient: 'carrageenan', severity: TriggerSeverity.high, category: TriggerCategory.gut, reason: 'Causes gut inflammation and microbiome disruption', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'enriched flour', severity: TriggerSeverity.high, category: TriggerCategory.gut, reason: 'Refined wheat, high GI, disrupts gut lining', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'bleached flour', severity: TriggerSeverity.high, category: TriggerCategory.gut, reason: 'Chemically processed wheat, gut irritant', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'sunflower oil', severity: TriggerSeverity.high, category: TriggerCategory.inflammatory, reason: 'Extremely high omega-6 ratio drives skin inflammation', affects: [TriggerAffect.skin, TriggerAffect.hair]),
  TriggerModel(ingredient: 'soybean oil', severity: TriggerSeverity.high, category: TriggerCategory.inflammatory, reason: 'Pro-inflammatory omega-6 dominance', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'vegetable oil', severity: TriggerSeverity.high, category: TriggerCategory.inflammatory, reason: 'Usually a seed oil blend, high omega-6', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'corn oil', severity: TriggerSeverity.high, category: TriggerCategory.inflammatory, reason: 'High linoleic acid, promotes chronic inflammation', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'cottonseed oil', severity: TriggerSeverity.high, category: TriggerCategory.inflammatory, reason: 'High omega-6, may carry pesticide residues', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'bha', severity: TriggerSeverity.high, category: TriggerCategory.inflammatory, reason: 'Synthetic antioxidant, possible endocrine disruptor', affects: [TriggerAffect.skin, TriggerAffect.hair]),
  TriggerModel(ingredient: 'bht', severity: TriggerSeverity.high, category: TriggerCategory.inflammatory, reason: 'Synthetic preservative with inflammatory potential', affects: [TriggerAffect.skin, TriggerAffect.hair]),
  TriggerModel(ingredient: 'whey', severity: TriggerSeverity.high, category: TriggerCategory.hormonal, reason: 'Strong IGF-1 stimulator, activates androgen pathway', affects: [TriggerAffect.skin, TriggerAffect.hair]),
  TriggerModel(ingredient: 'skim milk', severity: TriggerSeverity.high, category: TriggerCategory.hormonal, reason: 'Higher hormone concentration than whole milk', affects: [TriggerAffect.skin, TriggerAffect.hair]),
  TriggerModel(ingredient: 'partially hydrogenated', severity: TriggerSeverity.high, category: TriggerCategory.hormonal, reason: 'Trans fats are the strongest dietary DHT trigger', affects: [TriggerAffect.hair]),
  TriggerModel(ingredient: 'hydrogenated', severity: TriggerSeverity.high, category: TriggerCategory.hormonal, reason: 'Trans fats linked to elevated DHT and hair thinning', affects: [TriggerAffect.hair]),
  TriggerModel(ingredient: 'yeast extract', severity: TriggerSeverity.high, category: TriggerCategory.yeast, reason: 'Directly feeds Malassezia yeast, core seb derm trigger', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'autolyzed yeast', severity: TriggerSeverity.high, category: TriggerCategory.yeast, reason: 'Yeast-derived additive that promotes Malassezia growth', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'brewers yeast', severity: TriggerSeverity.high, category: TriggerCategory.yeast, reason: 'Active yeast trigger for seborrheic dermatitis', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'nutritional yeast', severity: TriggerSeverity.high, category: TriggerCategory.yeast, reason: 'Can exacerbate yeast imbalance in sensitive individuals', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'canola oil', severity: TriggerSeverity.medium, category: TriggerCategory.inflammatory, reason: 'Oxidizes easily when heated, becomes inflammatory', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'palm oil', severity: TriggerSeverity.medium, category: TriggerCategory.inflammatory, reason: 'Saturated fat, can trigger DHT elevation', affects: [TriggerAffect.hair]),
  TriggerModel(ingredient: 'sodium benzoate', severity: TriggerSeverity.medium, category: TriggerCategory.inflammatory, reason: 'Preservative linked to gut dysbiosis', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'msg', severity: TriggerSeverity.medium, category: TriggerCategory.inflammatory, reason: 'Can trigger inflammatory cascade in sensitive individuals', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'artificial flavors', severity: TriggerSeverity.medium, category: TriggerCategory.inflammatory, reason: 'Unknown compounds may disrupt gut microbiome', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'artificial colors', severity: TriggerSeverity.medium, category: TriggerCategory.inflammatory, reason: 'Synthetic dyes alter gut bacteria composition', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'milk', severity: TriggerSeverity.medium, category: TriggerCategory.gut, reason: 'IGF-1 spikes trigger sebum overproduction', affects: [TriggerAffect.skin, TriggerAffect.hair]),
  TriggerModel(ingredient: 'casein', severity: TriggerSeverity.medium, category: TriggerCategory.gut, reason: 'Dairy protein with inflammatory potential', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'wheat flour', severity: TriggerSeverity.medium, category: TriggerCategory.gut, reason: 'Gluten and high GI, dual gut trigger', affects: [TriggerAffect.skin]),
  TriggerModel(ingredient: 'gluten', severity: TriggerSeverity.medium, category: TriggerCategory.gut, reason: 'Increases intestinal permeability in sensitive individuals', affects: [TriggerAffect.skin, TriggerAffect.hair]),
];
